APP "HELLO-WORLD"
    PACKAGES { PF: "HTTPS://GITHUB.COM/ROC-LANG/BASIC-CLI/RELEASES/DOWNLOAD/0.8.1/X8URKVFYI9I0QHMVG98ROKBUS_AZRKLFWFJVJ3942YA.TAR.BR" }
    IMPORTS [PF.STDOUT]
    PROVIDES [MAIN] TO PF

MAIN = STDOUT.LINE FULLNAME "HELLO, " "JOHNNY" "CASH"

FULLNAME : STR, STR -> STR
FULLNAME = \FIRSTNAME, LASTNAME ->
    "$(FIRSTNAME) $(LASTNAME)"

FULLNAME2 = \FIRSTNAME, LASTNAME ->
    "$(FIRSTNAME) $(LASTNAME)"